site_name: Skyroad Dokumentation
site_url: https://skyroad.me/docs/
repo_url: https://github.com/abwasserrohr/SR-DOCS
edit_uri: https://github.com/Abwasserrohr/SR-DOCS/blob/main/docs/
use_directory_urls: false

extra:
  alternate:
    - name: Deutsch
      link: https://skyroad.me/docs/
      lang: de
  servervars:
    currencyname: Taler
    startcurrency: 250
    eventcurrency: Eventpunkte
    eventcurrencyshort: EP

theme:
  name: material
  language: de
  palette:
    primary: black
    accent: blue
  icon:
    repo: fontawesome/brands/github
  favicon: https://skyroad.me/wp-content/uploads/2021/02/cropped-skyroadlogosmaall-2-32x32.png
  logo: https://skyroad.me/wp-content/uploads/2021/02/cropped-skyroadlogosmaall.png
  features:
    - navigation.tabs

extra_css:
  - styles/styles.css
plugins:
  - search
  - macros
  - ezlinks:
      warn_ambiguities: true
      wikilinks: true
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - redirects:
      redirect_maps:
        introduction.md: README.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.snippets

extra_javascript:
