site_name: Skyroad Dokumentation
site_url: https://skyroad.me/docs/
repo_url: https://github.com/abwasserrohr/SR-DOCS
edit_uri: https://github.com/Abwasserrohr/SR-DOCS/blob/main/docs/
use_directory_urls: false

extra:
  #alternate:
  #  - name: Deutsch
  #    link: https://skyroad.me/docs/
  #    lang: de
  servervars:
    currencyname: Taler
    startcurrency: 250
    eventcurrency: Eventpunkte
    eventcurrencyone: Eventpunkt
    eventcurrencyshort: EP
    citybuild_back_price: 500
    citybuild_buyweather_clear_price: 250
    citybuild_buyweather_rain_price: 500
    citybuild_buyweather_thunder_price: 1000

theme:
  name: material
  language: de
  custom_dir: docs/home_theme/
  static_templates:
    - 404.html
  palette:
    - scheme: default
      primary: amber
      accent: orange
      toggle:
        icon: material/eye
        name: Wechsle in den dunklen Modus
    - scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: material/eye-outline
        name: Wechsle in den hellen Modus
  icon:
    repo: fontawesome/brands/github
  favicon: https://skyroad.me/wp-content/uploads/2021/02/cropped-skyroadlogosmaall-2-32x32.png
  logo: https://skyroad.me/wp-content/uploads/2021/02/cropped-skyroadlogosmaall.png
  features:
    - navigation.tabs

extra_css:
  - styles/styles.css
plugins:
  - search
  - macros
  - ezlinks:
      warn_ambiguities: true
      wikilinks: true
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - redirects:
      redirect_maps:
        introduction.md: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - https://cdn.plyr.io/3.6.8/plyr.js
